// <auto-generated />
namespace Website_BanQuanAo_HoHoangHuy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addMaLoaiSanPham : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMaLoaiSanPham));
        
        string IMigrationMetadata.Id
        {
            get { return "202310100316252_addMaLoaiSanPham"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
